Ft relate log and session 152919323
andela/wg-a-team pull request #17
Opened 2017-12-04 05:41 UTC by CeciliaCaroline

#### What does this PR do?
Set the work out log id as a foreign key in the workout sessions table.

#### Description of Task to be completed?
Create a foreign key relationship between the workout log and session

#### How should this be manually tested?
Query the workout log table in the database with the following commands`select * from manager_workoutlog;` 

#### Any background context you want to provide?
Right now the workout logs and the workout session are only linked through the date (for sessions this value is unique and enforced by the DB). This presents in some places a problem, since it's not possible to just follow a foreign key relationship with the ORM like in other places.

#### What are the relevant pivotal tracker stories?
#152919323

2017-12-04 06:15 UTC, VincentHokie approved these changes

2017-12-04 09:58 UTC, Sharonsyra reviewed
Nice work

2017-12-04 10:00 UTC, Sharonsyra commented
@CeciliaCaroline why are you merging to master?

2017-12-04 10:05 UTC, Sharonsyra commented
@CeciliaCaroline why the many files changed?

2017-12-07 07:17 UTC, jonathankamau commented on wger/manager/models.py
Why this space?

2017-12-07 07:25 UTC, jonathankamau requested changes
Your TravisCI build is failing. Please fix that.

2017-12-08 07:52 UTC, jonathankamau requested changes
This PR is almost ready for merging. change the PR title to `#152919323 Relate log and session` You don't  need to put `Ft` in the title. Also the PT ID in the PR description should be a link.

2017-12-08 08:53 UTC, CeciliaCaroline commented
PR title changed to #152919323 Relate log and session and PT ID changed to link

2017-12-08 12:00 UTC, jonathankamau requested changes
Please remove the migration files. They are not necessary anymore.

2017-12-08 12:17 UTC, CeciliaCaroline commented
@jonathankamau I removed the migrations in the last commit i made it was one of the causes of the merge conflict

2017-12-08 17:27 UTC, merged