Feature-Training info comparison between users
andela/wg-a-team pull request #18
Opened 2017-12-04 07:39 UTC by VincentHokie

#### What does this PR do?
It allows users compare their training data with another user on the application, also, new graphs have been used that show all 3 dimensions of the data being represented

#### Any background context you want to provide?
Previously users could only see data belonging to them and had no way of gauging themselves against other users, this is now possible with this PR

#### What are the relevant pivotal tracker stories?
152919324

#### Screenshots (if appropriate)
Previously, this is what the graphs looked like 
![new](https://user-images.githubusercontent.com/9318050/33540909-1f929978-d8de-11e7-963a-5db81175cf75.png)

![other](https://user-images.githubusercontent.com/9318050/33540913-22b41640-d8de-11e7-8ee1-e3fbdfffe127.png)

Now they look like this
<img width="619" alt="screen shot 2017-12-04 at 10 30 54" src="https://user-images.githubusercontent.com/9318050/33540945-40c6a5d0-d8de-11e7-9242-32a30683f8a9.png">

data under a date can be seen by clicking on a date
<img width="576" alt="screen shot 2017-12-04 at 10 31 21" src="https://user-images.githubusercontent.com/9318050/33540990-68d03884-d8de-11e7-90d0-a6ae83937046.png">

and when comparing data, a user is selected from a dropdown list and the graph reloads to look something like this

<img width="610" alt="screen shot 2017-12-04 at 10 33 07" src="https://user-images.githubusercontent.com/9318050/33541030-8ff0c53c-d8de-11e7-942c-9fb810f68371.png">

2017-12-04 07:50 UTC, CeciliaCaroline reviewed
Good use of graphs to compare data of different users

2017-12-06 08:19 UTC, Sharonsyra reviewed
Nice looks better

2017-12-07 07:05 UTC, jonathankamau reviewed
Were you able to implement the changes from Monday's demo because I don't see that reflected on the screenshots.

2017-12-07 07:08 UTC, jonathankamau reviewed
Why 96 files changed?

2017-12-07 07:09 UTC, jonathankamau commented on .gitignore
> +**/.DS_Store
New line required here.

2017-12-07 07:11 UTC, jonathankamau requested changes
Your build is failing on Travis CI. Please look into that.

2017-12-08 06:30 UTC, VincentHokie commented on .gitignore
> +**/.DS_Store
Done.

2017-12-08 06:31 UTC, VincentHokie commented
@jonathankamau the many files changed are mostly because of the ignored (and deleted in the git cache) migration files.

2017-12-08 06:52 UTC, jonathankamau commented on .travis.yml
> +    branch: develop
New line needed here.

2017-12-08 06:54 UTC, jonathankamau commented on wger/core/templates/tags/render_weight_log.html
> +</div>
New line required here.

2017-12-08 06:55 UTC, jonathankamau commented on wger/manager/templates/workout/log.html
> +{% endblock %}
New line needed here as well

2017-12-08 07:11 UTC, jonathankamau requested changes
Add the Pivotal Tracker ID to the title of your PR in this format `#PTID Training info comparison between users` You don't need `Feature` as part of the title.

2017-12-08 08:35 UTC, VincentHokie commented on .travis.yml
> +    branch: develop
Done.

2017-12-08 08:35 UTC, VincentHokie commented on wger/core/templates/tags/render_weight_log.html
> +</div>
Done.

2017-12-08 08:35 UTC, VincentHokie commented on wger/manager/templates/workout/log.html
> +{% endblock %}
aaand done.

2017-12-08 10:03 UTC, merged