Show all exercise info
andela/wg-a-team pull request #8
Opened 2017-11-24 10:01 UTC by ckwagaba

#152919317
Show all infos for an exercise.
There should be a new read-only API endpoint that collects all the information of an exercise such as muscles, category, images, etc. This makes it easier for clients to get all the infos since only a single request is needed to be done.

2017-11-30 13:43 UTC, Sharonsyra commented
@ckwagaba merge conflicts.

2017-12-04 09:45 UTC, Sharonsyra commented
@ckwagaba improve the structure of your PR. It needs to have different sections to it and at the same time explaining how to test it.

2017-12-06 05:14 UTC, Sharonsyra commented
@ckwagaba yet to see feedback implemented on this.

2017-12-06 09:05 UTC, ckwagaba commented
On it...

2017-12-06 09:22 UTC, ckwagaba commented
Hey, @Sharonsyra! Please review my PR.
Thanks.

2017-12-07 07:30 UTC, jonathankamau requested changes
You have conflicts on your PR. Please resolve.

2017-12-08 07:39 UTC, jonathankamau requested changes
You still have conflicts on this branch. Please resolve.

2017-12-08 07:40 UTC, jonathankamau requested changes
Make the PT ID a link as per the guidelines I have posted on the team channel.

2017-12-08 08:38 UTC, ckwagaba commented
PT ID made link. Resolving conflict...

2017-12-08 08:59 UTC, jonathankamau requested changes
Add the PT ID to your PR title so it appears like this: `#152919317 Show all exercise info`

2017-12-11 08:01 UTC, ckwagaba commented
@Sharonsyra and @jonathankamau I think I've made the changes. Please review again.
Thanks

2017-12-11 12:15 UTC, jonathankamau requested changes
The PR title still needs to be changed. I had posted this: `Add the PT ID to your PR title so it appears like this: '#152919317 Show all exercise info'`

2017-12-11 12:16 UTC, jonathankamau commented on settings.py
> +
You have two empty lines here.

2017-12-14 07:29 UTC, merged